### ISSUE TITLE
Suggestion - use a Pipfile

### ISSUE THREAD

**Issue by adorton-adobe** [bajwa-adobe/ust-configapp#2]
Instead of putting Python requirements in `requirements.txt`, we should consider defining requirements in a [Pipfile](https://github.com/pypa/pipfile).

Pipfile is a pretty new spec, but it will eventually [get built-in support in pip](https://github.com/pypa/pipfile#pip-integration-eventual).

For now Pipfile support is implemented in [pipenv](https://docs.pipenv.org/).  pipenv is recommended in [Python's official documentation](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies).

Here's a Pipfile I generated from the requirements file (after adding a missing dependency - see #1).

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

flask = "==0.12.2"
flask-cors = "==3.0.3"
"ruamel.base" = "==1.0.0"
"ruamel.yaml" = "==0.15.35"

[dev-packages]



[requires]

python_version = "3.6"
```
